version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    versioning-strategy: increase
    groups:
      vitest:
        patterns:
          - "*vitest*"
    cooldown:
      default-days: 5
      semver-major-days: 5
      semver-minor-days: 3
      semver-patch-days: 3
      include:
        - "*"
      exclude:
        - "@maplibre/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 3
      # no semver support for github-actions
      # => no specific configuration for this
      include:
        - "*"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
