services:
  build:
    platform: linux/amd64
    build:
      platforms:
        - "linux/amd64"
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    image: ghcr.io/maplibre/maplibre-gl-js:dev
    volumes:
      - ./:/maplibre-gl-js/

  dev:
    image: ghcr.io/maplibre/maplibre-gl-js:dev
    working_dir: /maplibre-gl-js
    volumes:
      - ./:/maplibre-gl-js/
    ports:
      - 9966:9966
    command: npm run start

  test:
    image: ghcr.io/maplibre/maplibre-gl-js:dev
    volumes:
      - ./test/:/maplibre-gl-js/test/
    command: npm run test-unit
