services:
  dev:
    privileged: true
    platform: linux/amd64
    image: localhost/maplibre-gl-js
    build:
      platforms:
        - "linux/amd64"
    working_dir: /maplibre-gl-js
    volumes:
      - ./src/:/maplibre-gl-js/src/
      - ./dist/:/maplibre-gl-js/dist/
    ports:
      - 9966:9966

  test:
    privileged: true
    platform: linux/amd64
    image: localhost/maplibre-gl-js
    volumes:
      - ./test/:/maplibre-gl-js/test/
    command:
      - /bin/bash
      - -c
      - |
        npm run test-unit

