services:
  build:
    platform: linux/amd64
    build:
      platforms:
        - "linux/amd64"
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    image: ghcr.io/maplibre/maplibre-gl-js-dev

  dev:
    # platform: linux/amd64
    # image: localhost/maplibre-gl-js
    image: ghcr.io/maplibre/maplibre-gl-js-dev
    working_dir: /maplibre-gl-js
    volumes:
      - ./:/maplibre-gl-js/
    ports:
      - 9966:9966
    command:
      - /bin/bash
      - -c
      - |
        npm ci
        npm run build-css
        npm run build-dev
        npm run start-server &
        npm run watch-dev

  test:
    # platform: linux/amd64
    image: localhost/maplibre-gl-js
    volumes:
      - ./test/:/maplibre-gl-js/test/
    command:
      - /bin/bash
      - -c
      - |
        npm run test-unit
