services:
  dev:
    platform: linux/amd64
    image: localhost/maplibre-gl-js
    build:
      platforms:
        - "linux/amd64"
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    working_dir: /maplibre-gl-js
    volumes:
      - ./:/maplibre-gl-js/
    ports:
      - 9966:9966
    command:
      - /bin/bash
      - -c
      - |
        npm ci
        npm run watch-css
        npm run watch-dev

  test:
    platform: linux/amd64
    image: localhost/maplibre-gl-js
    volumes:
      - ./test/:/maplibre-gl-js/test/
    command:
      - /bin/bash
      - -c
      - |
        npm run test-unit
