@startuml
actor user
participant DOM
participant handler_manager
participant handler
participant camera
participant transform
participant map

user->>camera: map#setCenter, map#panTo
camera->>transform: update
camera->>map: fire move event
map->>map: _render()

user->>DOM: resize, pan,\nclick, scroll,\n...
DOM->>handler_manager: DOM events
handler_manager->>handler: forward event
handler-->>handler_manager: HandlerResult
handler_manager->>transform: update
handler_manager->>map: fire move event
map->>map: _render()
@enduml
