name: All Test Render

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test_render_ubuntu:
    strategy:
      fail-fast: false
      matrix:
        ref:
          - f87090b70b8a6fbde1a779c44933ce32bffc5d2c
          - 49bc4ca45aba6b6af98df7e1e91735dcb0d6f20f
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.ref }}
      - name: Use Node.js 10 x64
        uses: actions/setup-node@v2
        with:
          node-version: 10
          architecture: x64
      - run: npm ci
      - run: npm run build-dev
      - run: xvfb-run -s "-ac -screen 0 1280x1024x24" npm run test-render
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-render-ubuntu-latest-$${ matrix.ref }.html
          path: test/integration/render-tests/index.html

  test_render_win_mac:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
        node_version:
          - 10
        architecture:
          - x64
        ref:
          - f87090b70b8a6fbde1a779c44933ce32bffc5d2c
          - 49bc4ca45aba6b6af98df7e1e91735dcb0d6f20f

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.ref }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
      - run: npm ci
      - run: npm run build-dev
      - run: npm run test-render
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-render-${{ matrix.os }}-$${ matrix.ref }}.html
          path: test/integration/render-tests/index.html
      
