# After a build completes, this workflow analyzes the artifacts and reports back in a comment

name: Analyze

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  check-size:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: hmarr/debug-action@v1.0.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
      - run: yarn install --frozen-lockfile
      - name: Download branch artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: dist
          path: after
          repo: msbarry/maplibre-gl-js-fork
      - name: Download base artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          workflow: build.yml
          commit: ${{ github.event.workflow_run.pull_requests[0].base.sha }}
          name: dist
          path: before
          repo: msbarry/maplibre-gl-js-fork
      - run: yarn source-map-explorer before/mapbox-gl.js --gzip --json before.json
      - run: yarn source-map-explorer after/mapbox-gl.js --gzip --json after.json
      - name: Build bundle size report
        run: node build/check-bundle-size.js > comment-body.txt
      - name: Dump bundle size report
        run: cat comment-body.txt

      - id: get-comment-body
        run: |
          body=$(cat comment-body.txt)
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo ::set-output name=body::$body

      # Attempt to post a comment with the bundle size report on the PR
      # Or update the comment on subsequent changes
      - name: Find Comment
        uses: peter-evans/find-comment@v1
        continue-on-error: true
        id: fc
        with:
          issue-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          comment-author: "github-actions[bot]"
          body-includes: Bundle size report

      - name: Create comment
        continue-on-error: true
        if: ${{ steps.fc.outputs.comment-id == 0 }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          body: ${{ steps.get-comment-body.outputs.body }}

      - name: Update comment
        continue-on-error: true
        if: ${{ steps.fc.outputs.comment-id != 0 }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: ${{ steps.get-comment-body.outputs.body }}
          edit-mode: replace
