name: publish-style-spec

on:
  workflow_dispatch

jobs:
  build_publish:
    name: Build, publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 14 x64
        uses: actions/setup-node@v2
        with:
          node-version: 14
          architecture: x64
          registry-url: 'https://registry.npmjs.org'

      - name: Install GL JS
        run: npm ci
      
      - name: Build GL JS
        run: |
          npm run build-prod-min
          npm run build-css
      
      - name: Build style spec
        run: |
          npm run build-style-spec
          cp -r dist/style-spec/ src/style-spec/dist
      
      - name: Check version and publish
        run: |
          cd src/style-spec
          node -e "if(require('./package').version.includes('dev')) { process.exit(1) }"
          npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ORG_TOKEN }}
