name: Remove PR Demo

on:
  pull_request:
    types: [closed]

jobs:
  remove-pr-demo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: gh-pages

    - name: Remove folder 
      run: git rm -rf pulls/${{ github.event.number }}

    - name: Commit and push
      run: |
        git config --global user.name 'bot'
        git config --global user.email 'email@example.com'
        git commit -am "Remove ${{ github.event.number }}"
        git push
    - name: Add comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: pr-demo
        message: |
          Removed build output and live demo.
