name: Integration Test - Style Spec

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test_style_spec:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16 x64
        uses: actions/setup-node@v2
        with:
          node-version: 16
          architecture: x64
      - run: npm ci
      - run: npm run build-dev
      - run: xvfb-run -s "-ac -screen 0 1280x1024x24" npm run test-style-spec
