name: Test Expressions

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test_expressions:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14 x64
        uses: actions/setup-node@v2
        with:
          node-version: 14
          architecture: x64
      - run: npm ci
      - run: npm run build-dev
      - run: npm run test-expressions
